<h1>Mørke og Vintermeditasjon</h1>
<p>Vi trenger vinteren - er jeg i ferd med å oppdage, for å føle en naturlig vei innover i oss selv. Årstidens stillhet, den iboende sakteheten gir nødvendige pauser i naturens så vel som vår egen livsrytmen – hvis vi tillater oss å kjenne etter og ta imot. Mørketid er god meditasjonstid.</p>

<p>Slik trærne har satt knopper klare for neste vårslepp, men nå har trukket livs-sevjen tilbake for å vente, er det tid for å være tilstede - i våken hvile. Jeg fornemmer smaken av sårbar sanselighet. Sittende en stille en mørk morgenstund med oppmerksomheten vendt innover føles det helt merkbart i egen puls.
Etter år med solid motstand mot kulde, is , sne og endeløst med mørke, kunne jeg rundt november kjenne at jeg ”trengte en vinter”. Ord så fremmede at jeg hvertfall ikke sa dem høyt til noen. Høsten seg innpå, lengre og lengre, til sakte og stille, nattlige døgn. Jeg skjønte etterhvert at jeg trengte å kjenne den ru barken, se tegningene av trestammer oppover med spredningen av grenene mot grålig himmelen. Få direkte kontakt med skjelettet, strukturene, av det som er under, sommertidens fremvisning av kronens løvverk og fargeprakt. Turer i svinnende lys er min gående meditasjon i nærvær med naturen på utsiden, såvel som innsiden.</p>

<p>Til min forskrekkelse oppdaget jeg at når jeg blir med inn i natten og ikke rømmer inn i Tv, gis jeg våken stillhet. Jeg får morgner i mild ro med følelsen av å være svøpt elfenbenssort silke. Måtte jeg bli så voksen for å erfare dette? Er alder nødvendig, eller er bare noen av oss trege, så fulle av uvitenhet om vinterens gaver? Det er en stemning av beskjedenhet i mørket, noe helt annet enn tropisk natt jeg er oppvokst med. Nordisk vintermørke er inadvendt i sin virkning. Det presser seg ikke på. Mens vi lyser opp alt vi kan i gater og hus for slippe å se at farger blir borte og farer rundt som om alle årstider er det samme, så må vi nå føle oss frem…. hvis vi mediterer på det som faktisk skjer i naturen. Som en ærlig nybegynner i disse vintergledene kan jeg virkelig si at jeg ikke ante det hadde noen hensikt med lange måneder avskåret fra det jeg mener er liv. Jeg er fortsatt ikke komfortabel med kulden, skremmende berg av pakket sne eller isholke. Men, min relativt nyvunne oppdagelse av den meditative nytten av vinteren må jeg dele. </p>

<p>Jeg har skrevet og snakket om pustepauser og vennlighet for seg selv. Vel, naturen gir oss det helt ubetinget og i raust monn – hvis vi tar det innover oss. Jeg elsker sannheten i at knopper er satt, trærne vet det kommer en vår og forbereder seg allerede etter løvfall med å sette de små på hver en gren. Og, så tar de vel fortjent hvilepause. Metaforene er mange og kjente om naturens svangerskap med nytt liv som vokser i indre mørke. Parallellene til vår psyke er åpenbare. Men, det å faktisk føle naturens vintermeditasjon fra innsiden er en ferskere tilføyelse i min tilværelse. Det å faktisk ta inn på alvor, ikke bare være redd for vinteren, men gå forbi det umiddelbare i kulde og is, og ta inn det overveldende rommet av stillhet, som naturen skaper for oss i sin fløyelsemyke kappe av transparent sorthet. På fjellet har jeg vinterstid sett himmelvelvingen glitrende av stjerner. Jeg har sett på det, med ære og forundring, men frykten for dette grenseløse der ute har alltid fått meg til å skynde meg hutrende inn i hytten til peisvarmen. </p>
<p>Det er plass til denne stillheten på innsiden i meg... Det er som år med opptatthet av hva tilstedeværelse er umerkelig har smeltet innover så jeg oppdager huler av stillhet. Som grenenes tydelige tegninger mot himmelen kan jeg kjenne klarhet i sinnet, ro - for det er virkelig ikke noe sted å reise eller vei til noe mål. Jeg faller ikke bakover til litenhet eller gråhet, men innover til storhet hvor jeg rommes. 
<p>Det er med forundring at vinteren var det jeg manglet. Som febrilsk identifisert med vår og sommer har jeg ikke skjenket vinteren en god tanke siden jeg kom til Norge som tenåring. Den har alltid vært fienden av farger, undertrykkeren av liv, begrensningen av all bevegelse. Ja, vinteren gjør alt dette men, det er jo ikke feil. Det er en større virkning bortenfor kulden. Beklager jeg er så sen med å forstå hva nordiske forfattere og malere har formidlet, men jeg tror ikke jeg er alene om å være så dum. Vi lever i en kultur hvor alt fokus er på det lysende, det utadvendte, det synlige, det fargerike ( sant eller påtatt), det hørbare, og slik at vi har gjort en vesentlig dimensjon i vår eksistens til non gratie, uønsket. Vi later som den ikke er der ved å insistere på elektrisitet til hele døgnet. Vi beveger oss i kunstig lys, bokstavelig talt, tett nede på bakken som under et teppe, hvor vi ikke vil vite av en storhet vi ikke kjenner. </p>

<p>Mørket er muligheten til å se hva som bærer oss fra innsiden. Meditasjon har lært meg det, men vinteren fordyper dette. Å stå avkledd, naken, utsatt for nådeløs kulde, ikke fordi vinteren vil oss vondt, men ganske enkelt fordi det er et aspekt av vår tilværelse, å stå innfor det større miraklet av vår eksistens på denne kloden. Å se sine bare grener og vite at du må vente. Å bli kjent med din egen krokethet, merke hvor grenene er trøtte og nok brekker av ved neste stormkast, samt kjenne styrken i egen stamme. Stamme, som referer både til metaforen for vår individuelle kropp, og til gruppen vi føler slektskap og tilhørighet til. Og vi er ikke sterkere enn det svakeste leddet, men våger vi se det når vi er avkledd i oss selv?</p>
Det gir trygghet, på et forunderlig vis, å se sine bare grener. Det er ikke farlig å kjenne virkelighetens kulde rett på huden når man hviler i visshet om at man står, man har struktur, man har sin individuelle form og integritet, som ingen kan ta fra deg. Og, man har sevje, som uavhengig av om du fortjener det eller ikke, vil stige opp til våren igjen og igjen, og igjen. Nyt vinteren, bli kjent med ditt mørke rom, se ditt indre for det det er, se innenfor redsel og forestillinger om hva som burde være der, vær nysgjerrig på det større, som mørket holder for deg -og se hvordan mørket lyser.</p>
Jeg satt denne vintermorgen og skrev disse ordene fordypet, og så forsiktig, forsiktig og sakte, som bare en nordisk vinterdag kan åpne seg merket jeg lyset finne sin styrke. Jeg rakk å være der når dagen tonet himmelen i lys gråblå . Jeg var der når dagen utfoldet seg.

<p>Vil du lære å meditere og være mindfull – subtilt tilstedeværende med sanselighet? Jeg har noen tiårs erfaring å dele fra. Ta gjerne kontakt for en time eller så : christine@schjetlein.no